---
title: "Assignment3"
author: "Jack"
date: "2024-10-01"
output: html_document
---

# 1. Visualisation
```{r include=FALSE}
library(tidyverse)
library(Stat2Data)
data("Hawks")
```


## 1.1 Q1
```{r include=TRUE}
hawksSmall <- drop_na(select(Hawks,Age,Day,Month,Year,CaptureTime,Species,Wing,Weight,Tail))
print(head(hawksSmall,5))
print(dim(hawksSmall))
```


## 1.1 Q2
```{r}
hawksSmall_weight <- ggplot(data=hawksSmall, aes(x=Weight))
hawksSmall_weight + geom_histogram(binwidth=10) + ylab("Count")
```


## 1.1 Q3
```{r}
hawksSmall_density <- ggplot(data=hawksSmall, aes(x=Tail)) + xlab("Tail Length")
hawksSmall_density + geom_density(adjust=0.5) + ylab("Count")
hawksSmall_density + geom_density(adjust=2) + ylab("Count")
```

**These plots have different modes. There are 3 modes in plot with adjust 0.5 and there are 2 modes in plot with adjust 2**


## 1.1 Q4
```{r}
ggplot(data=hawksSmall, aes(x=Tail, color=Species)) + geom_density(adjust=2) + xlab("Tail length") + ylab("Count")
```


## 1.1 Q5
```{r}
ggplot(data=hawksSmall, aes(x=Tail, y=Species, fill=Species)) + geom_violin() + theme_bw() + xlab("Tail (mm)") +ylab("Density")
```


## 1.1 Q6
```{r}
hawksMass <- ggplot(data=hawksSmall, aes(y=Weight,x=Tail)) + xlab("Tail (mm)") + ylab("Weight (mm)")
hawksMass + geom_point(aes(color=Species, shape=Species)) + theme_bw()
```
**1. aesthetics: Species -> color, Species -> shape, Tail -> x, Weight -> y,**

**2. glyphs: points**

**3. Shape Color**


## 1.1 Q7
```{r}
hawksMass + geom_point(aes(color=Species)) + theme_bw() + facet_wrap(~Species, scales="free") +geom_smooth(method="lm",aes(color=Species))
```
**1. Area color Direction**

**2. Proportional**


## 1.1 Q8
```{r}
heaviest <- max(filter(hawksSmall)$Weight, na.rm=TRUE)
print(heaviest)
hawksMass + geom_point(aes(color=Species)) + theme_bw() + geom_curve(x=190,xend=196,y=1800,yend=2040,arrow=arrow(length=unit(0.5,'cm')),curvature=0.1) + geom_text(x=180,y=1790,label="heaviest hawk")
```


# 2. Finite probability spaces

## 2.1 Q1
${{22}\choose{z}} \cdot 3^z \cdot 7^{22-z}$


## 2.1 Q2
```{r}
pro_red_spheres <- function(z){
  stopifnot(is.numeric(z),z>=0)
  A <- choose(22,z) * 3^z * 7^(22-z)
  result <- A/(10^22)
  return (result)
}
print(pro_red_spheres(10))
```


## 2.1 Q3
```{r}
num_reds <- c()
prob <- c()
for (x in 1:22){
  num_reds <- append(num_reds,x)
  prob <- append(prob,pro_red_spheres(x))
}
prob_by_num_reds <- data.frame(num_reds,prob)
prob_by_num_reds %>% head(3)
```


## 2.1 Q4
```{r}
ggplot(prob_by_num_reds, aes(x=num_reds,y=prob)) + geom_line() + xlab("Number of reds") + ylab("Probability")
```


## 2.1 Q5

```{r}
# case 1: Setting the random seed just once
set.seed(0)
for(i in 1:5){
  print(sample(100,5,replace=FALSE))
}

# case 2: Resetting the random seed every time
set.seed(1)
print(sample(100,5,replace=FALSE))
set.seed(1)
print(sample(100,5,replace=FALSE))
set.seed(1)
print(sample(100,5,replace=FALSE))

# case 3: reproducing case 1 if we set a random seed at the beginning
set.seed(0)
for(i in 1:5){
  print(sample(100,5,replace=FALSE))
}
# The result will be 5 samples same as in case 1, because they have the same seed
```

```{r}
itermap <- function(.x,.f){
  result <- list()
  for (item in .x) {
    result <- c(result, list(.f(item)))
  }
  return (result)
}
itermap(c(1,2,3),function(x){return (c(x,x^2))})

itermap_dbl <- function(.x,.f) {
  result <- numeric(length(.x))
  for(i in 1:length(.x)){
    result[i] <- .f(.x[[i]])
  }
  return (result)
}
itermap_dbl(c(1,2,3), function(x){return (x^3)})
```

```{r}
trial <- sequence(1000)
set.seed(0)
sampling_with_replacement_simulation <- data.frame(trial) %>% mutate(sample_balls = itermap(.x=trial,function(x){sample(10,22,replace=TRUE)}))

sampling_with_replacement_simulation <- sampling_with_replacement_simulation %>% mutate(num_reds = itermap_dbl(.x=trial,function(x){
  n <- 0
  for (i in sampling_with_replacement_simulation[[x,"sample_balls"]]){
  if (i <= 3){n <- n+1}
  }
  return (n)
  }
  ))
head(sampling_with_replacement_simulation,5)
```


## 2.1 Q6
```{r}
# we extract a vector corresponding to the number of reds in each trial
num_reds_in_simulation <- sampling_with_replacement_simulation %>% pull(num_reds)
# add a column which gives the number of trials with a given number of reds
prob_by_num_reds<-prob_by_num_reds %>% mutate(predicted_prob=itermap_dbl(.x=num_reds, function(.x) sum(num_reds_in_simulation==.x))/1000)
print(prob_by_num_reds)
```


## 2.1 Q7
```{r}
prob_by_num_reds %>% rename(TheoreticalProbability=prob, EstimatedProbability=predicted_prob) %>% ggplot(aes(x=num_reds)) + theme_bw() + geom_line(aes(y=TheoreticalProbability)) + geom_line(aes(y=EstimatedProbability), linetype="dashed") + geom_point(aes(y=EstimatedProbability)) + xlab("Number of reds") + ylab("Probabilities")
```


# 2.2 Q1
```{r}
# 1. Random seed
set.seed(0)

# 2. set a number of trials
trials <- sequence(100)

# 3. generate samples
spheres <- c(rep("Red", 50), rep("Blue", 30), rep("Green", 20))
sampling_without_replacement_simulation <- data.frame(trials) %>% mutate(sample_balls = itermap(.x=trials,function(x){sample(spheres,10,replace=TRUE)}))

# 4. Compute the number of red, green, and blue
# Red
sampling_without_replacement_simulation <- sampling_without_replacement_simulation %>% mutate(num_reds = itermap_dbl(.x=trials,function(x){
  n <- 0
  for (i in sampling_without_replacement_simulation[[x,"sample_balls"]]){
  if (i == "Red"){n <- n+1}
  }
  return (n)
  }
  ))

# Green
sampling_without_replacement_simulation <- sampling_without_replacement_simulation %>% mutate(num_greens = itermap_dbl(.x=trials,function(x){
  n <- 0
  for (i in sampling_without_replacement_simulation[[x,"sample_balls"]]){
  if (i == "Green"){n <- n+1}
  }
  return (n)
  }
  ))

#Blue
sampling_without_replacement_simulation <- sampling_without_replacement_simulation %>% mutate(num_blues = itermap_dbl(.x=trials,function(x){
  n <- 0
  for (i in sampling_without_replacement_simulation[[x,"sample_balls"]]){
  if (i == "Blue"){n <- n+1}
  }
  return (n)
  }
  ))
print(sampling_without_replacement_simulation)

# 5. Compute the minimum of the three counts
sampling_without_replacement_simulation["min_colors"] <- pmin(sampling_without_replacement_simulation["num_reds"],sampling_without_replacement_simulation["num_greens"],sampling_without_replacement_simulation["num_blues"])
print(sampling_without_replacement_simulation)

# 6. Compute  the proportion of rows for which the minimum number of the three counts is zero
zero <- 0
for (i in sampling_without_replacement_simulation[["min_colors"]]){
  if (i == 0){
    zero <- zero + 1
  }
}
proportion <- zero/length(trials)
print(proportion)
```


## 2.2 Q2
```{r}
subset <- choose(100,10)

miss_red <- choose(50,10)
miss_blue <- choose(70,10)
miss_green <- choose(80,10)
miss_red_blue <- choose(20,10)
miss_red_green <- choose(30,10)
miss_blue_green <- choose(50,10)

# avoid double count
miss_one_or_two_colors <- miss_red + miss_green + miss_blue - miss_blue_green - miss_red_green - miss_red_blue

pro <- miss_one_or_two_colors / subset
print(pro)
```





